- admin/general-tab.php
- admin/js/links-tab.js
- admin/js/reporting-tab.js
- admin/links-tab-docs.php
- admin/links-tab.php
- disciple-tools-magic-links.php
- magic-link/magic-link-user-app.php
- magic-link/magic-links-api.php
- magic-link/magic-links-cron.php
- magic-link/magic-links-default-filters.php
- rest-api/rest-api.php
> V2 Core Features

- magic-link/magic-link-templates.php
> #21 - Use POST Request Methods To Support Large Payloads

- admin/js/templates-tab.js
- admin/templates-tab.php
- disciple-tools-bulk-magic-link-sender.php
- magic-link/magic-link-templates.php
- version-control.json
> #24 - Template Custom Field Label Translations

- composer.json
- disciple-tools-bulk-magic-link-sender.php
- magic-link/magic-link-templates.php
- version-control.json
> #32 - Force Editable Custom Template Fields

- admin/links-tab.php
- disciple-tools-bulk-magic-link-sender.php
- magic-link/magic-links-cron.php
- version-control.json
> #35 - Resolved Scheduling Links Issue

- magic-link/magic-link-post-type.php
- magic-link/magic-link-templates.php
- magic-link/magic-link-user-app.php
- magic-link/magic-link-user-posts-base.php
- magic-link/magic-links-api.php
> #45 - Submission Visual Confirmation

- admin/js/templates-tab.js
- admin/templates-tab-docs.php
- admin/templates-tab.php
- magic-link/magic-link-templates.php
> #46 - Send Submission Notifications

- magic-link/magic-link-user-posts-base.php
Could be causing some caching issues I've had reported.
> set cache-control header on posts list request

- magic-link/magic-link-user-app.php
- magic-link/magic-link-user-groups-app.php
> #66 - Resolved Apostrophe Failures In Post Names

- magic-link/magic-links-default-filters.php
fixes: #77 
---
- Switched over to using `WP_Queue`, to better manage large volume based email dispatching.
> #77 - Email Not Arriving

- admin/js/links-tab.js
- admin/links-tab.php
- magic-link/magic-links-api.php
- rest-api/rest-api.php
> #65 - Ability To Renew Extend Link Expiration Dates

- magic-link/magic-link-post-type.php
- magic-link/magic-link-templates.php
- magic-link/magic-link-user-app.php
- magic-link/magic-link-user-posts-base.php
- magic-link/magic-links-api.php
- fixes: #79 
- Existing success toasts also updated to support new parameter-based shape.
> #79 - Failure Toasts On Update Submission

- admin/js/links-tab.js
- admin/links-tab.php
> #82 - Ordering For Assigned Users, Teams & Groups

- magic-link/magic-link-templates.php
- magic-link/magic-link-user-posts-base.php
- magic-link/magic-links-api.php
> ML#89 - Form Field Submission Validation Feature

- magic-link/magic-link-templates.php
> ML#92 - Custom Text Fields Not Showing

- magic-link/magic-link-post-type.php
- magic-link/magic-link-templates.php
- magic-link/magic-link-user-app.php
- magic-link/magic-link-user-posts-base.php
- magic-link/magic-links-api.php
> ML#91 - Explored PHP Echoed JS Code Alternatives

- admin/js/links-tab.js
> ML#93 - Cannot Uncheck Group Updates Connection Fields

- admin/js/templates-tab.js
- admin/templates-tab-docs.php
- admin/templates-tab.php
- magic-link/magic-link-templates.php
- fixes: #87 
---
- A new `List Sub-Assigned Contacts` Template Details Setting has now been introduced; which enables users to toggle the displaying of assigned contacts associated to smart link's target owner.
> ML#87 - Smart Link Templates - Display List Of Assigned Contacts

- admin/js/templates-tab.js
- admin/templates-tab.php
- magic-link/magic-link-templates.php
> ML#109 / ML#110 - Template Updates

- admin/templates-tab.php
- magic-link/magic-link-templates.php
Addressed signed-out templates subassigned display uncaught exception issue + Ensure ignored field types are not shown within form
> Signed-Out Templates Exception Issue + Hide Ignored Field Types

- composer.json
- disciple-tools-bulk-magic-link-sender.php
- magic-link/magic-links-default-filters.php
> ML#116 - Ensure Expired Links Remain Invalid

- magic-link/magic-link-templates.php
- magic-link/magic-link-user-posts-base.php
> ML#119 - Investigate Localised Field Settings

- magic-link/magic-link-templates.php
- magic-link/magic-link-user-app.php
- magic-link/magic-link-user-posts-base.php
> ML#127 - Updated Magic Link Submit Workflow

- magic-link/magic-links-api.php
> ML#124 - Ensure Expired Links Fail Gracefully

- admin/js/links-tab.js
- admin/links-tab.php
- magic-link/magic-links-api.php
- rest-api/rest-api.php
> ML#129 - Links Tab Takes A Long Time To Open

- magic-link/magic-link-templates.php
> ML#141 - Location Field In Template Not Working

- admin/js/templates-tab.js
- admin/templates-tab.php
- magic-link/magic-link-templates.php
- magic-link/magic-link-user-app.php
> ML#151 - Ability To Create Records

- magic-link/magic-link-templates.php
> ML#154 - Template - List Sub-Assigned Contacts Not Returning Assigned Contacts

- magic-link/magic-link-user-app.php
- magic-link/magic-link-user-posts-base.php
> ML#159 - Group & User Magic Links

- admin/admin-menu-and-tabs.php
- admin/email-tab.php
- admin/general-tab.php
- admin/links-tab.php
- admin/logging-tab.php
- admin/reporting-tab.php
- admin/templates-tab.php
- composer.json
- disciple-tools-bulk-magic-link-sender.php
- includes/class-migration-engine.php
- includes/migrations/0000-initial.php
- includes/migrations/0001-link-object-v1-upgrade.php
- includes/migrations/abstract.php
- magic-link/magic-link-post-type.php
- magic-link/magic-link-user-app.php
- magic-link/magic-link-user-login-app.php
- magic-link/magic-link-user-posts-base.php
- magic-link/magic-links-api.php
- magic-link/magic-links-cron.php
- phpcs.xml
Update PHPCS coding standards based on starter template
> Phpcs standards

- admin/templates-tab.php
- disciple-tools-bulk-magic-link-sender.php
- magic-link/magic-link-templates.php
- magic-link/templates/create-record.php
https://github.com/user-attachments/assets/1e373bb4-15c8-476a-9bc3-dfee39e26f2c
> New Magic Link template type for creating records.
